// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo3d: typeof import('./src/components/demo-3d.vue')['default']
    Demo3d1: typeof import('./src/components/demo-3d-1.vue')['default']
    Demo3d2: typeof import('./src/components/demo-3d-2.vue')['default']
    Demo3d3: typeof import('./src/components/demo-3d-3.vue')['default']
    Dialog: typeof import('./src/components/oasisengine-demo/components/dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JoyStick: typeof import('./src/components/oasisengine-demo/components/JoyStick.vue')['default']
    Loading: typeof import('./src/components/oasisengine-demo/components/loading.vue')['default']
    OasisengineDemo: typeof import('./src/components/oasisengine-demo/index.vue')['default']
    Play_screan: typeof import('./src/components/oasisengine-demo/components/play_screan.vue')['default']
    ProcessBar: typeof import('./src/components/oasisengine-demo/components/process-bar.vue')['default']
    StartPage: typeof import('./src/components/oasisengine-demo/components/start-page.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    Video: typeof import('./src/components/video.vue')['default']
  }
}
